using Microsoft.EntityFrameworkCore; 
using BangazonAPI.Models;

namespace BangazonAPI.Data
{
    public class BangazonAPIContext : DbContext
    {
        public BangazonAPIContext(DbContextOptions<BangazonAPIContext> options)
            : base(options)
        { }

//this is where you set the database relationship to the tables
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Product> Products { get; set; } //jk-setting up a relationship between the database and the products table

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // If a model has a date field that should be generated by the database
            modelBuilder.Entity<Customer>()
                .Property(b => b.DateAccountCreated)
                .HasDefaultValueSql("strftime('%Y-%m-%d %H:%M:%S')");

            modelBuilder.Entity<Product>()  //jk-Created this model builder so a time is automatically generated when a product is added to the database
                .Property(b => b.DateProductAdded)
                .HasDefaultValueSql("strftime('%Y-%m-%d %H:%M:%S')");

        }
    }
}